name: "Build and deploy"
on:
  pull_request:
    types:
      - closed

  workflow_dispatch:

jobs:
  deploy:
    env:
      DOCKER_IMAGE: "tomasstorc/meteostation:latest"
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "build fe"
        run: |
          cd frontend
          npm i
          npm run build
          cd ..
      - name: "copy builded fe"
        run: |
          mkdir -p backend/fe
          cp -r frontend/build/* backend/fe/

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "docker build"
        run: docker build . -t ${{ env.DOCKER_IMAGE }}

      - name: "docker push"
        run: docker push ${{ env.DOCKER_IMAGE }}

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MS_APP_ID }}
          tenant-id: ${{ secrets.MS_TENANT_ID }}
          subscription-id: ${{ secrets.MS_SUB_ID }}

      - name: "restart app"
        run: |
          az webapp restart -n meteo-station -g meteo-rg
