name: "test"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ignore_warnings:
        description: "ignore warnings"
        required: true
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          export CI=true
          cd frontend
          npm install
          npm run build
        if: ${{ github.event.inputs.ignore_warnings == 'false' }}
        name: "run test, do not skip warnings"
      - run: |
          export CI=false
          cd frontend
          npm install
          npm run build
        if: ${{ github.event.inputs.ignore_warnings == 'true' }}
        name: "run test, skip warnings"
