name: "run workflow"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: tomasstorc/devops/actions/terraform-validate@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
